name: Build and Package Release

on:
  push:
    tags:
      - '*' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    # Build Go backend binary
    - name: Build Go binary
      run: |
        VERSION=$(git describe --tags)
        cd backend
        go build -ldflags "-X 'version.Version=${VERSION}'" -o main .

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    # Install dependencies and build Vue frontend
    - name: Build Vue frontend
      run: |
        cd frontend
        npm install
        npm run build-only

    # Gather migration files
    - name: Copy migration files
      run: |
        mkdir -p /home/runner/work/migrations
        cp -r backend/data/db/migrations/* /home/runner/work/migrations/

    # Create a zip with all necessary artifacts
    - name: Create a zip file with artifacts
      run: |
        mkdir -p release
        cp backend/main release/
        cp -r frontend/dist release/
        cp -r /home/runner/work/migrations release/
        cd release
        zip -r release-package.zip *

    # Upload the release package as an artifact
    - name: Upload Release Artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-package
        path: release/release-package.zip
