name: Build and Package Release

on:
  push:
    tags:
      - '*' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    # Build Go backend binary
    - name: Build Go binary
      run: |
        VERSION=$(git describe --tags)
        cd backend
        go build -ldflags "-X 'github.com/${{ github.repository }}/version.Version=${VERSION}'" -o main .

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    # Install dependencies and build Vue frontend
    - name: Build Vue frontend
      run: |
        cd frontend
        npm install
        npm run build-only

    # Gather migration files
    - name: Copy migration files
      run: |
        mkdir -p /home/runner/work/migrations
        cp -r backend/data/db/migrations/* /home/runner/work/migrations/

    # Create a zip with all necessary artifacts
    - name: Create a zip file with artifacts
      run: |
        mkdir -p release
        cp backend/main release/
        cp -r frontend/dist release/
        cp -r /home/runner/work/migrations release/
        cd release
        zip -r release-package.zip *

    # Create a GitHub release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: Description of the release
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    # Upload the release package as an asset to the GitHub release
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/release-package.zip
        asset_name: release-package.zip
        asset_content_type: application/zip
