name: Recreate Release on Go File Changes

on:
  push:
    branches:
      - main

jobs:
  check-go-files:
    runs-on: ubuntu-latest
    outputs:
      go_files_changed: ${{ steps.changed-backend-files.outputs.any_changed }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get changed files in the backend folder
        id: changed-backend-files
        uses: tj-actions/changed-files@v45
        with:
          files: backend/**/**.go

      - name: Run step if any file(s) in the backend folder change
        if: steps.changed-backend-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-backend-files.outputs.all_changed_files }}
        run: |
          echo "One or more files in the backend folder has changed."
          echo "List all the files that have changed: $ALL_CHANGED_FILES"

  recreate-release:  
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Delete the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete "0.0.0" --cleanup-tag
          git tag 0.0.0
          git push origin 0.0.0
          
          release_body="Automated release"
          response=$(curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"tag_name":"0.0.0","name":"0.0.0","body":"Automated release"}' \
            "https://api.github.com/repos/DigiConvent/testd9t/releases")

          echo "Release created successfully: $response"
