name: Recreate Release on Go File Changes

on:
  push:
    branches:
      - main

jobs:
  check-go-files:
    runs-on: ubuntu-latest
    outputs:
      go_files_changed: ${{ steps.changed-backend-files.outputs.any_changed }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get changed files in the backend folder
        id: changed-backend-files
        uses: tj-actions/changed-files@v45
        with:
          files: backend/**/**.go

      - name: Run step if any file(s) in the backend folder change
        if: steps.changed-backend-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-backend-files.outputs.all_changed_files }}
        run: |
          echo "One or more files in the backend folder has changed."
          echo "List all the files that have changed: $ALL_CHANGED_FILES"

  recreate-release:
    # needs: check-go-files
    # if: needs.check-go-files.outputs.go_files_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Delete the init tag
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: 0.0.0
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Recreate Tag
        run: |
          git tag $RELEASE_TAG
          git push origin $RELEASE_TAG

      - name: Create New Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $RELEASE_TAG --title "Release $RELEASE_TAG" --notes "Automatically recreated release."

